### ISSUE TITLE
Fails to write changes when only block entities have been changed

### ISSUE THREAD

**Issue by dranorter** [alex4200/PyBlock#2]
Hello! Thank you for your library!

I am trying to migrate a modpack and my situation is that capitalization has changed on some NBT data.

In other words, I am searching through all inventories in a Minecraft world, and trying to replace the lowercase "items" tags with the proper "Items" tags.

Player inventories are already corrected, so what remains is to search block entities. Your library looked ideal for that.

My strategy is to try and get every chunk to load, by requesting a block from every chunk:

```
world = pyblock.Editor('')

# Force load all chunks
for x_pos in range(-25000, 25000, 16):
    for z_pos in range(-25000, 25000, 16):
        world.get_block(x_pos, 0, z_pos)
```

Next, I search through all loaded block entities, and of course check for an inventory, etc. If I find a tag that needs to be corrected, I write the change and then add the entity to the list of entities that need updated:

```
if str(entity['Items'][i]['id']) == 'simple_backpack:backpack':
    # Change capitalization
    entity['Items'][i]['tag']['backpack']['Items'] = entity['Items'][i]['tag']['backpack']['items']
    # Save to list of pending updates
    region_coords, chunk_coords, _, _ = pyblock.tools.block_to_id_index(entity['x'].value, entity['y'].value, entity['z'].value)
    key = (region_coords, chunk_coords)
    world.entities[key].append(entity)
```
(This is simplified; my code recursively checks tags in case inventories are nested.)

Then of course when I'm done, I call `world.done()` to write all changes.

## The Issue

Calling `world.done()` in my code does not save any changes, because `world.done()` is looking for changes in `world.blocks_map`. I haven't created any such changes, because I didn't move or copy block entities, I only wanted to make changes to their tags.

## Expected Behavior

I would like to suggest that the library should save changes in these cases. What's tricky (from my uninformed POV) is actually changing the block entity rather than adding a duplicate.

**Comment by alex4200** [comment]
Thanks for trying my library, I am happy when it is of use!

I cannot promise to look into your suggestion right away, but I will keep it in my mind. I certainly will come back to you later!

**Comment by alex4200** [comment]
Hello @dranorter, I have looked into this issue and can provide a possible workaround for now - if this is still relevant. If this workaround works, I can implement it as a more permanent solution. 

You should use your code to get the list of all entities in your world. Then instead of calling `world.done()` you run the following code:


```

from collections import defaultdict

# First, sort the entities by region
entities_per_region = defaultdict(list)
for key, entities in world.entities.items():
    region_coord, chunk_coord = key
    entities_per_region[region_coord].append((chunk_coord, entities))

# Then write the data just for the chunks with the updated entities (if no other block information has changed)
for region_coord, entities_per_chunk in entities_per_region.items():
    # Read the data for the given region
    region = pyblock.Region(world.path, region_coord)

    updated_chunks = {}
    for chunk_coord, entities in entities_per_chunk:
        # Get the chunk
        chunk = region.get_chunk(chunk_coord)
        # Store the manipulated chunk
        updated_chunks[chunk_coord] = chunk.get_bytes(entities)
    # write the region with the updated chunks
    region.write(updated_chunks)
```

Please give it a try (in a test world).

**Comment by dranorter** [comment]
Ah awesome, thank you! I'll give it a try tonight or tomorrow.

**Comment by dranorter** [comment]
It works! I'd written something very similar myself without getting it properly working, so I was genuinely afraid it wouldn't work. Many thanks!

**Comment by alex4200** [comment]
@dranorter Cool good to know it works. 

Let me know if anything else shows up, or if you have questions or suggestions. Please open another ticket in that case. Thanks
